package org.example;



import java.security.SecureRandom;
import java.util.Base64;

public class SessionGenerator {//open class
    private static final SecureRandom secureRandom = new SecureRandom(); //provides a cryptographic strong random number
    private static final Base64.Encoder base64Encoder = Base64.getUrlEncoder().withoutPadding(); //produces a url-safe strings without padding

    //used tp generate an encrypted session token
    public static String generateSessionToken()
    {//open method
        byte[] randomBytes = new byte[32]; //256-bit token
        secureRandom.nextBytes(randomBytes); //filling byte array with random generated bytes
        return base64Encoder.encodeToString(randomBytes); //encoding the bytes
    } //close

}//close class
